"""Initial AI Studio schema baseline.

Revision ID: 20260628_0001
Revises:
Create Date: 2026-06-28
"""

from alembic import op
import sqlalchemy as sa


revision = "20260628_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "chats",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "title",
            sa.String(length=255),
            nullable=False
        ),
        sa.Column(
            "is_pinned",
            sa.Boolean(),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "id"
        )
    )

    op.create_table(
        "global_documents",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False
        ),
        sa.Column(
            "stored_filename",
            sa.String(length=255),
            nullable=False
        ),
        sa.Column(
            "file_type",
            sa.String(length=20),
            nullable=False
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True
        ),
        sa.Column(
            "chunk_count",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "text_length",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "stored_filename"
        )
    )

    op.create_index(
        "ix_global_documents_status",
        "global_documents",
        [
            "status"
        ],
        unique=False
    )

    op.create_table(
        "documents",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "chat_id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=False
        ),
        sa.Column(
            "stored_filename",
            sa.String(length=255),
            nullable=False
        ),
        sa.Column(
            "file_type",
            sa.String(length=20),
            nullable=False
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "status",
            sa.String(length=30),
            nullable=False
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True
        ),
        sa.Column(
            "chunk_count",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "text_length",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            [
                "chat_id"
            ],
            [
                "chats.id"
            ]
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "stored_filename"
        )
    )

    op.create_index(
        "ix_documents_chat_id",
        "documents",
        [
            "chat_id"
        ],
        unique=False
    )

    op.create_index(
        "ix_documents_status",
        "documents",
        [
            "status"
        ],
        unique=False
    )

    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "chat_id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "role",
            sa.String(length=50),
            nullable=False
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False
        ),
        sa.Column(
            "model",
            sa.String(length=100),
            nullable=True
        ),
        sa.Column(
            "mode",
            sa.String(length=50),
            nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            [
                "chat_id"
            ],
            [
                "chats.id"
            ]
        ),
        sa.PrimaryKeyConstraint(
            "id"
        )
    )

    op.create_index(
        "ix_messages_chat_id",
        "messages",
        [
            "chat_id"
        ],
        unique=False
    )

    op.create_table(
        "global_document_chunks",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "global_document_id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "chunk_index",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False
        ),
        sa.Column(
            "embedding",
            sa.JSON(),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            [
                "global_document_id"
            ],
            [
                "global_documents.id"
            ]
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "global_document_id",
            "chunk_index",
            name="uq_global_document_chunk_index"
        )
    )

    op.create_index(
        "ix_global_document_chunks_global_document_id",
        "global_document_chunks",
        [
            "global_document_id"
        ],
        unique=False
    )

    op.create_table(
        "document_chunks",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "document_id",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "chunk_index",
            sa.Integer(),
            nullable=False
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False
        ),
        sa.Column(
            "embedding",
            sa.JSON(),
            nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False
        ),
        sa.ForeignKeyConstraint(
            [
                "document_id"
            ],
            [
                "documents.id"
            ]
        ),
        sa.PrimaryKeyConstraint(
            "id"
        ),
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_document_chunk_index"
        )
    )

    op.create_index(
        "ix_document_chunks_document_id",
        "document_chunks",
        [
            "document_id"
        ],
        unique=False
    )


def downgrade():
    op.drop_index(
        "ix_document_chunks_document_id",
        table_name="document_chunks"
    )
    op.drop_table(
        "document_chunks"
    )

    op.drop_index(
        "ix_global_document_chunks_global_document_id",
        table_name="global_document_chunks"
    )
    op.drop_table(
        "global_document_chunks"
    )

    op.drop_index(
        "ix_messages_chat_id",
        table_name="messages"
    )
    op.drop_table(
        "messages"
    )

    op.drop_index(
        "ix_documents_status",
        table_name="documents"
    )
    op.drop_index(
        "ix_documents_chat_id",
        table_name="documents"
    )
    op.drop_table(
        "documents"
    )

    op.drop_index(
        "ix_global_documents_status",
        table_name="global_documents"
    )
    op.drop_table(
        "global_documents"
    )

    op.drop_table(
        "chats"
    )
